version: '2'

services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: mysecretpassword
  memcached:
    image: memcached:latest
    ports:
      - 11211:11211
