version: '2'

services:
  auth:
    image: jboss/keycloak
    ports: 
      - 5000:8080
    environment:
      DB_VENDOR: postgres
      DB_ADDR: db:5432
      DB_DATABASE: dailystandup_development
      DB_USER: postgres
      DB_PASSWORD: mysecretpassword
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: foobar
    depends_on:
      - db


  redis:
    image: redis:latest
    ports:
      - 6379:6379
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: mysecretpassword
  memcached:
    image: memcached:latest
    ports:
      - 11211:11211
