version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

dependencies:
	pre:
		- pip install awsebcli

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7
    executor: ruby/default
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: test the enc
          command: cat config/credentials/production.yml.enc
      - run:
          name: Build it
          command: make build
