version: 2.1
jobs:
  dependencies:
    pre:
      - pip install awsebcli
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Config EBS
          command: eb use dailystandup-prod-vpc --profile default
      - run:
          name: Buildit and Shippit
          command: make deploy_pipeline
