version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7
    executor: ruby/default
    steps:
      - setup_remote_docker:
         docker_layer_caching: true
      - checkout
      - run:
          name: Build it
          command: make build
