version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Config EBS
          command: |
            echo "$DOCKER_PASS" | docker login -u $DOCKER_USER --password-stdin
            sudo pip install --upgrade awsebcli
            eb init dailystandup --region us-east-1 -p 'Docker 18.09.9-ce'
      - run:
          name: Buildit and Shippit
          command: make deploy_pipeline
