version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: test the enc
          command: cat config/credentials/production.yml.enc
      - run:
          name: install ebcli
          command: pip install awsebcli
      - run:
          name: Config EBS
          command: eb use dailystandup-prod-vpc --profile default
      - run:
          name: Buildit and Shippit
          command: make deploy_pipeline
